[properties]

[constants]
preprocessor_definitions = []

[project options]
wrap_mode = 'nofallback'
bindir = 'bin'
sbindir = 'bin'
libexecdir = 'bin'
includedir = 'include'
libdir = 'lib'


[binaries]
c = 'gcc'
cpp = 'g++'

[built-in options]
buildtype = 'release'
b_ndebug = 'true'
cpp_std = 'c++20'
backend = 'ninja'
pkg_config_path = '/workspace/docker-build'
# C/C++ arguments
c_args = ['-m64'] + preprocessor_definitions
c_link_args = ['-m64']
cpp_args = ['-m64'] + preprocessor_definitions
cpp_link_args = ['-m64']

